import { Kire } from "kire";
import KireTailwind from "./src";

const kire = new Kire();

kire.plugin(KireTailwind);

Bun.serve({
    port: 3000,
    async fetch(req) {
        console.log("Request received");
        try {
            const html = await kire.render(`
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Kire Tailwind Example</title>
                    @tailwind
                        @import "tailwindcss";
                        
                        @theme {
                          --color-clifford: #da373d;
                        }

                        .btn {
                            @apply px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 cursor-pointer;
                        }
                        
                        .clifford {
                            color: var(--color-clifford);
                            @apply font-bold text-xl;
                        }
                    @end
                </head>
                <body class="p-10 font-sans">
                    <h1>Tailwind Integration Test</h1>
                    <p class="clifford">
                        This text uses a custom theme color (clifford) and @@apply.
                    </p>
                    <br>
                    <button class="btn">
                        Styled Button
                    </button>
                    
                    <div class="mt-8 p-4 bg-gray-100 rounded">
                        <p>The styles above are generated by compiling the CSS string passed to @@tailwind block.</p>
                        <p>This confirms that <code>compile</code>, <code>loadStylesheet</code>, and <code>childrenRaw</code> are working.</p>
                    </div>
                </body>
                </html>
            `);

            return new Response(html, {
                headers: {
                    "Content-Type": 'text/html'
                }
            });
        } catch (e) {
            console.error("Render error:", e);
            return new Response("Internal Server Error\n" + e, { status: 500 });
        }
    }
})